CREATE TABLE IF NOT EXISTS buku (
    id INT AUTO_INCREMENT PRIMARY KEY,
    judul VARCHAR(255) NOT NULL,
    penulis VARCHAR(255) NOT NULL,
    tahunTerbit INT NOT NULL,
    isbn VARCHAR(100) NOT NULL UNIQUE
);